version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: patent-db
    environment:
      POSTGRES_DB: patent_assessment
      POSTGRES_USER: patent_user
      POSTGRES_PASSWORD: patent_dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patent_user -d patent_assessment"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and session storage  
  redis:
    image: redis:7-alpine
    container_name: patent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: patent-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://patent_user:patent_dev_password@postgres:5432/patent_assessment
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - ./docs:/app/docs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: patent-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: patent-assessment-network